name: PannelAppDB
channels:
  - defaults
dependencies:
  - pip == 23.3  
  - requests == 2.31.0
  - pandas == 2.1.1 
  - pytest == 7.4.0 
  - coverage == 7.2.2
  - responses == 0.13.3
  - numpy==1.26.3
  - SQLAlchemy==2.0.25
  - tabulate==0.9.0 
  - sphinx>=4.3.0
  - sphinx-rtd-theme>=0.5.1